### ISSUE TITLE
Tabs Implementation Errors

### ISSUE THREAD

**Issue by Tokuriku** [joshuha/Fantasy-Grounds-foundations-core#5]
Extensive Job on the Tabs!
But I get a few errors that I think I should point out:

I get an error saying that the "Tabs" vertical anchor in the NPC charsheet is not set.
I also get a "attempt to call field 'getIndex' (a nil value) error trying to open the mini sheet.

**Comment by phantomwhale** [comment]
Fixed the getIndex error with this pull : https://github.com/joshuha/Fantasy-Grounds-foundations-core/pull/7

Cannot recreate the vertical anchor warning - check you've pulled the latest code (as it used to exist)

**Comment by Tokuriku** [comment]
I can attest to the gatIndex error being fixed.

As for the vertical anchor:
I've downloaded the ruleset separately by hand as it is right now and it still gives me the warning.

**Comment by phantomwhale** [comment]
Hmmmm... I couldn't see it. Have reopened for now, will try and pull down a fresh copy from the master branch and take a look again later

**Comment by kirbyimk** [comment]
Was getting this error as well with the ruleset I modified. I fixed the problem by removing the old tab code (tab subwindows) and adding the new tab registration.
